### ISSUE TITLE
如何配置允许所有 ip 通过 gnb ？

### ISSUE THREAD

**Issue by foobartech** [gnbdev/gnb_build#3]
软件：bin/openwrt/ramips-mt7621

route.conf
```
1001|10.1.0.1|255.255.255.0
1001|192.168.1.0|255.255.255.0
1001|0.0.0.0|0.0.0.0
1002|10.1.0.2|255.255.255.0
1003|10.1.0.3|255.255.255.0
```
在 1002 上 ping 1001 的内网地址 10.1.0.1 或者 192.168.1.1 都 ok，ping 8.8.8.8 不行(已配置对应路由和允许转发)，配置地址和子网掩码为 `0.0.0.0` 没有效果，请教一下是配置有误还是软件限制？

**Comment by gnbdev** [comment]
是的，不支持全流量转发
