### ISSUE TITLE
win的版本请求超时呢

### ISSUE THREAD

**Issue by 201841301322** [gnbdev/gnb_build#5]
win的版本请求超时呢
ping 10.1.0.2

22-05-09 15:34:13 PF pf_tun_route_cb [1003]>[1002] pf_ctx->in_ttl[0] route_frame_head->ttl[5] ip_frame_size[60]
22-05-09 15:34:18 PF pf_tun_route_cb [1003]>[1002] pf_ctx->in_ttl[0] route_frame_head->ttl[5] ip_frame_size[60]
22-05-09 15:34:23 PF pf_tun_route_cb [1003]>[1002] pf_ctx->in_ttl[0] route_frame_head->ttl[5] ip_frame_size[60]
22-05-09 15:34:28 PF pf_tun_route_cb [1003]>[1002] pf_ctx->in_ttl[0] route_frame_head->ttl[5] ip_frame_size[60]

C:\Users\XXX>ping 10.1.0.2

正在 Ping 10.1.0.2 具有 32 字节的数据:
请求超时。
请求超时。
请求超时。
请求超时。

10.1.0.2 的 Ping 统计信息:
    数据包: 已发送 = 4，已接收 = 0，丢失 = 4 (100% 丢失)，

ipconfig情况是
以太网适配器 以太网 2:

   连接特定的 DNS 后缀 . . . . . . . :
   IPv6 地址 . . . . . . . . . . . . : 64:ff9b::a01:3
   本地链接 IPv6 地址. . . . . . . . : fe80::98cd:e48:6199:4f54%27
   IPv4 地址 . . . . . . . . . . . . : 10.1.0.3
   子网掩码  . . . . . . . . . . . . : 255.255.0.0
   默认网关. . . . . . . . . . . . . :

**Comment by 201841301322** [comment]
我在Linux上的10.1.0.1是可以ping通10.1.0.2的

**Comment by gnbdev** [comment]
请阅读用户手册

https://github.com/gnbdev/opengnb/blob/master/docs/gnb_user_manual_cn.md

发自我的iPhone

**Comment by Brice2012** [comment]
我用windows的这个编译版也是ping不通，看linux下成功的提示，
感觉是不是 -b "D:\ProgGSoft/gnb.9001.map"  这个地方的路径不正确导致没法返回其他节点的index信息？？？

win下不成功的：
22-06-13 17:20:00 INDEX_SERVICE start gnb_index_service_worker success!
22-06-13 17:20:00 INDEX HANDLE ECHO addr ***.89.33.38
22-06-13 17:20:01 CORE exec gnb_es argv '"D:\openGnb\gnb_es.exe" -b "D:\ProgGSoft/gnb.9001.map" --upnp'
22-06-13 17:20:35 PF pf_tun_route_cb [1005]>[1001] pf_ctx->in_ttl[0] route_frame_head->ttl[5] ip_frame_size[60]

linux下的成功的：

22-06-08 17:07:38 INDEX_SERVICE start gnb_index_service_worker success!
22-06-08 17:07:38 DETECT start gnb_detect_worker success!
22-06-08 17:07:38 INDEX HANDLE ECHO addr ***.52.73.72
22-06-08 17:07:38 INDEX RECEIVE_PUSH_ADDR node=1001 ***.这里是IP:9001 text='INDEX PUSH ADDR[1001]=>[1002]' action=C
22-06-08 17:07:38 INDEX send DETECT 1002 ==> 1001 address ***..这里是IP:9001 port range[25]
22-06-08 17:07:38 INDEX RECEIVE_PUSH_ADDR node=1001 ***..这里是IP:9001 text='INDEX PUSH ADDR[1001]=>[1002]' action=C
22-06-08 17:07:39 CORE exec gnb_es argv '/usr/local/src/opengnb/gnb_es -b /tmp/gnb.9001.map --upnp'
22-06-08 17:07:53 NODE handle_ping_frame IPV4 src[1001]->dst[1002] idx=0 ***..这里是IP:9001 now=1654****50 src_ts=16546****721 up=1 different=1***9

**Comment by gnbdev** [comment]
没有所谓的请求超时的概念

QQ微信同号 26253


发自我的iPhone

**Comment by gnbdev** [comment]
提供的信息太少，可以根据文档和对比日志找出问题，邮件已经回复。
